// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMiRt5bI_6eJnqKDdzmIWVvLdQ4-maUSI',
    appId: '1:941184590133:web:781ce2fceed878471f6c7c',
    messagingSenderId: '941184590133',
    projectId: 'fasum-app-33f0c',
    authDomain: 'fasum-app-33f0c.firebaseapp.com',
    storageBucket: 'fasum-app-33f0c.appspot.com',
    measurementId: 'G-6NM0WCW2NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz7BZkbXpBm-4IwvSiHdxIOLHofVdbbaA',
    appId: '1:941184590133:android:f49668c925d331ca1f6c7c',
    messagingSenderId: '941184590133',
    projectId: 'fasum-app-33f0c',
    storageBucket: 'fasum-app-33f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_enF4himPRo2MYzeKsJLRlZRlSMJp8Y',
    appId: '1:941184590133:ios:604792a1abdcf8391f6c7c',
    messagingSenderId: '941184590133',
    projectId: 'fasum-app-33f0c',
    storageBucket: 'fasum-app-33f0c.appspot.com',
    androidClientId: '941184590133-i0bq0fdicekj6qsh7bkdcmtce6c9gge3.apps.googleusercontent.com',
    iosClientId: '941184590133-e1pqldp2jb2m3enq5eq2a2slq4e5o9vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz_enF4himPRo2MYzeKsJLRlZRlSMJp8Y',
    appId: '1:941184590133:ios:604792a1abdcf8391f6c7c',
    messagingSenderId: '941184590133',
    projectId: 'fasum-app-33f0c',
    storageBucket: 'fasum-app-33f0c.appspot.com',
    androidClientId: '941184590133-i0bq0fdicekj6qsh7bkdcmtce6c9gge3.apps.googleusercontent.com',
    iosClientId: '941184590133-e1pqldp2jb2m3enq5eq2a2slq4e5o9vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMiRt5bI_6eJnqKDdzmIWVvLdQ4-maUSI',
    appId: '1:941184590133:web:52db8fa438ac8d481f6c7c',
    messagingSenderId: '941184590133',
    projectId: 'fasum-app-33f0c',
    authDomain: 'fasum-app-33f0c.firebaseapp.com',
    storageBucket: 'fasum-app-33f0c.appspot.com',
    measurementId: 'G-35RZYFRMB2',
  );

}